imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/admin/routing_stage.yml"

monolog:
    handlers:
        main:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: info
