imports:
    - { resource: sulu.yml }
    - { resource: security.yml }
    - { resource: ../config.yml }
    - { resource: ../widgets.yml }

# Assetic Configuration
assetic:
    bundles: [ ClientWebsiteBundle ]

# Doctrine Configuration
doctrine:
    orm:
        dql:
            string_functions:
                CAST: Sulu\Component\Rest\DQL\Cast

# SULU Content Configuration
sulu_content:
    preview:
        mode: auto
        websocket: false
        delay: 200

# SULU Admin Configuration
sulu_admin:
    name: %sulu_admin.name%
    email: %sulu_admin.email%

# Just a dirty hack to get the jms serializer bundle correctly working
# https://github.com/schmittjoh/JMSSerializerBundle/pull/270#issuecomment-21171800
parameters:
    jms_serializer.cache_naming_strategy.class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy

# SULU Contact Configuration
sulu_contact:
    form_of_address:
        male:
            id: 0
            name: male
            translation: contact.contacts.formOfAddress.male
        female:
            id: 1
            name: female
            translation: contact.contacts.formOfAddress.female

# Massive Build Configuration
massive_build:
    targets:
        prod:
            dependencies:
                database: ~
                phpcr: ~
                fixtures: ~
        dev:
            dependencies:
                database: ~
                fixtures: ~
                phpcr: ~
                user: ~
        maintain:
            dependencies:
                node_order:
                search_index:

# SULU Contact Extension Configuration
# define the account types and form of address
# tabs key must match tab-id specified in content-navigation
sulu_contact_extension:
    account_types:
        basic:
            id: 0
            name: basic
            translation: contact.account.type.basic
            tabs:
                financials: false
            convertableTo:
                lead: true
                customer: true
        lead:
            id: 1
            name: lead
            translation: contact.account.type.lead
            tabs:
                financials: false
            convertableTo:
                customer: true
        customer:
            id: 2
            name: customer
            translation: contact.account.type.customer
            tabs:
                financials: true
        supplier:
            id: 3
            name: supplier
            translation: contact.account.type.supplier
            tabs:
                financials: true
