imports:
    - { resource: parameters.yml }
    - { resource: services.yml }
    - { resource: sulu.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/%sulu.context%/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        ['ClientWebsiteBundle']
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        server_version: "%database_version%"
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            gedmo_tree:
                type: "xml"
                prefix: "Gedmo\Tree\Entity"
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                alias: "GedmoTree" # this one is optional and will default to the name set for the mapping
                is_bundle: false
        resolve_target_entities:
            Sulu\Component\Security\Authentication\UserInterface: Sulu\Bundle\SecurityBundle\Entity\User
            Sulu\Bundle\ProductBundle\Entity\ProductInterface: Sulu\Bundle\ProductBundle\Entity\Product
            Sulu\Component\Security\Authentication\RoleInterface: Sulu\Bundle\SecurityBundle\Entity\Role
            Sulu\Bundle\MediaBundle\Entity\CollectionInterface: Sulu\Bundle\MediaBundle\Entity\Collection
            Sulu\Bundle\ContactBundle\Entity\AccountInterface: Sulu\Bundle\ContactExtensionBundle\Entity\Account
            Sulu\Bundle\Sales\CoreBundle\Entity\OrderAddressInterface: Sulu\Bundle\Sales\CoreBundle\Entity\OrderAddress
            Sulu\Bundle\Sales\CoreBundle\Entity\ItemInterface: Sulu\Bundle\Sales\CoreBundle\Entity\Item
            Sulu\Bundle\Sales\OrderBundle\Entity\OrderStatusInterface: Sulu\Bundle\Sales\OrderBundle\Entity\OrderStatus
            Sulu\Bundle\Sales\OrderBundle\Entity\OrderInterface: Sulu\Bundle\Sales\OrderBundle\Entity\Order
        dql:
            string_functions:
                group_concat: Oro\ORM\Query\AST\Functions\String\GroupConcat

# Doctrine Extension Configuration
stof_doctrine_extensions:
    orm:
        default:
            tree: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# LIIP Theme Configuration
liip_theme:
    themes: ["default"]
    active_theme: "default"
    load_controllers: false
    assetic_integration: true

# SULU Core Configuration
sulu_core:
    locales: ["de","en"]
    phpcr:
        backend:    "%phpcr_backend%"
        workspace:  "%phpcr_workspace%"
        username:   "%phpcr_user%"
        password:   "%phpcr_pass%"
    webspace:
        config_dir: "%kernel.root_dir%/Resources/webspaces"
    content:
        structure:
            default_type:
                snippet: "default"
                page: "default"
            paths:
                app_page:
                    path: "%kernel.root_dir%/Resources/pages"
                    internal: false
                    type: "page"
                app_snippet:
                    path: "%kernel.root_dir%/Resources/snippets"
                    internal: false
                    type: "snippet"
                sulu:
                    path: "%kernel.root_dir%/../vendor/sulu/sulu/src/Sulu/Bundle/CoreBundle/Content/templates"
                    internal: true
                    type: "page"

# SULU Media configuration
sulu_media:
    search:
        enabled: true

# SULU Websocket configuration
sulu_websocket:
    server:
        http_host: %websocket_url%
        port: %websocket_port%

# Symfony CMF Configuration
cmf_core:
    publish_workflow:
        enabled: false

# SULU HTTP Cache configuration
sulu_http_cache:
    handlers:
        paths:
            enabled: true
        public:
            max_age: 240
            shared_max_age: 240
            use_page_ttl: true
            enabled: true
        debug:
            enabled: %kernel.debug%
    proxy_client:
        symfony:
            enabled: true

sulu_content:
    search:
        mapping:
            Sulu\Component\Content\Structure\Page:
                index: page
                category: page
            Sulu\Component\Content\Structure\Snippet:
                index: snippet
                category: snippet

massive_search:
    localization_strategy: index
    persistence:
        doctrine_orm:
            enabled: true
doctrine_cache:
   providers:
       phpcr_meta:
           type: %phpcr_cache%
       phpcr_nodes:
           type: %phpcr_cache%

# SULU Product configuration
sulu_product:
    template: ClientWebsiteBundle:views:product.html.twig
