imports:
    - { resource: sulu.yml }
    - { resource: security.yml }
    - { resource: ../config.yml }

# Assetic Configuration
assetic:
    bundles:        [ ClientWebsiteBundle ]

# Symfony CMF Configuration
cmf_routing:
    chain:
        routers_by_id:
            router.default: 100
            cmf_routing.dynamic_router: 25
    dynamic:
        enabled: true
        route_provider_service_id: sulu_website.provider.content
