sulu_media:
    resource: "@SuluMediaBundle/Resources/config/routing_website.yml"

sulu_product:
    resource: "@SuluProductBundle/Resources/config/routing_website.yml"
    type: portal

client_website:
    type: portal
    resource: "@ClientWebsiteBundle/Resources/config/routing.yml"

sulu_search:
    type: portal
    resource: "@SuluSearchBundle/Resources/config/routing_website.xml"

sulu_website:
    resource: "@SuluWebsiteBundle/Resources/config/routing_website.yml"
